WHITE = '#FFFFFF'

BACKGROUND_COLOR = '#D3D5E7'
HOVER_COLOR = '#DBE7FE'
PRESSED_COLOR = '#EEEDF2'
TEXT_COLOR = '#1E247E'

MAIN_BACKGROUND = '#79CAA1'

TOP_FRAME_BACKGROUND = '#79CAA1'

CLOSE_BACKGROUND = '#DA867D'
CLOSE_HOVER = '#EDC4BF'
CLOSE_PRESSED = '#C94E40'

MINIMIZE_BACKGROUND = '#F0C330'
MINIMIZE_HOVER = '#F6DE8D'
MINIMIZE_PRESSED = '#AB860D'

OUTER_CIRCLE_COLOR = '#79CAA1'
INNER_CIRCLE_COLOR = '#79CAA1'
RADIOBUTTON_HOVER = '#D3EEE0'
RADIOBUTTON_TEXT_COLOR = '#1E247E'

ICON = 'assets/icon.png'
ICON_MEDIUM = 'assets/icon_medium.png'
ICON_SMALL = 'assets/icon_small.png'