BACKGROUND_COLOR = '#D3D5E7'
HOVER_COLOR = '#DBE7FE'
PRESSED_COLOR = '#EEEDF2'
TEXT_COLOR = '#1E247E'

MAIN_BACKGROUND = '#79CAA1'

CLOSE_BACKGROUND = '#DA867D'
CLOSE_HOVER = '#EDC4BF'
CLOSE_PRESSED = '#C94E40'

MINIMIZE_BACKGROUND = '#F0C330'
MINIMIZE_HOVER = '#EDC4BF'
MINIMIZE_PRESSED = '#AB860D'

ICON = 'assets/icon.png'
ICON_MEDIUM = 'assets/icon_medium.png'
ICON_SMALL = 'assets/icon_small.png'